// Markdown -> sanitized, block-id-stamped body HTML. Node-only (uses jsdom).
// Locked engine: markdown-it@14 with a constrained plugin chain.
// `html:false` in the markdown path means raw HTML inside .md is escaped; a raw-HTML
// FILE is a separate input that always passes through the sanitizer first.

import MarkdownIt from "markdown-it";
import anchor from "markdown-it-anchor";
import taskLists from "markdown-it-task-lists";
import GithubSlugger from "github-slugger";
import type { PageInput, RenderResult } from "../types.js";
import { assignBlockIds, extractToc, firstHeading } from "../blocks.js";
import { getNodeSanitizer, parseFragment } from "../sanitize/node.js";

function buildMarkdownIt(): MarkdownIt {
  // github-slugger matches GitHub anchors exactly for unicode/punctuation/duplicates, so deep
  // links stay stable. Fresh per render so the de-dupe counter resets per document.
  const slugger = new GithubSlugger();
  const md = new MarkdownIt({ html: false, linkify: true, typographer: true });
  md.use(anchor, { level: [1, 2, 3], slugify: (s: string) => slugger.slug(s), permalink: false });
  md.use(taskLists, { enabled: true, label: true, labelAfter: true });
  return md;
}

/** Render a page input into a sanitized, addressable body. */
export function render(input: PageInput, fallbackTitle: string): RenderResult {
  let bodyHtml: string;
  if (input.kind === "markdown") {
    bodyHtml = buildMarkdownIt().render(input.source);
  } else {
    // Raw HTML file: host as-is, but NEVER bypass the sanitizer.
    bodyHtml = getNodeSanitizer().sanitizeHtml(input.source);
  }

  const body = parseFragment(bodyHtml);

  // Markdown was generated by our trusted pipeline (html:false), so the markdown path
  // does not need a second sanitize; the raw-HTML path was already sanitized above.
  const blockIds = assignBlockIds(body);
  const toc = extractToc(body);
  const title = firstHeading(body) || fallbackTitle;

  return { html: body.innerHTML, toc, blockIds, title };
}
